# Generated by Django 5.0.6 on 2024-08-08 06:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=20)),
                ('tax_percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('gst_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(15)])),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=10)),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('supply_product', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_sub_name', models.CharField(blank=True, default=' ', max_length=255, null=True)),
                ('image', models.FileField(upload_to='foodimage')),
                ('price', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('stock', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('product_BV', models.FloatField()),
                ('stock_alert_value', models.FloatField(default=0)),
                ('price_before_tax', models.FloatField(blank=True, null=True)),
                ('tax_amount', models.FloatField(blank=True, null=True)),
                ('tax', models.CharField(choices=[('Inclusive', 'Inclusive'), ('Exclusive', 'Exclusive')], max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ecom.productcategory')),
                ('tax_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.tax')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='foodimage')),
                ('is_primary', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ecom.product')),
            ],
        ),
    ]
