# Generated by Django 5.0.6 on 2024-08-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_primary',
            field=models.FileField(blank=True, null=True, upload_to='product_image'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_s1',
            field=models.FileField(blank=True, null=True, upload_to='product_image'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_s2',
            field=models.FileField(blank=True, null=True, upload_to='product_image'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
