# Generated by Django 5.0.6 on 2024-08-08 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_product_image_primary_product_image_s1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
