# Generated by Django 5.0.6 on 2024-08-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_deliveryaddress_order_orderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
