# Generated by Django 5.0.6 on 2024-08-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_alter_deliveryaddress_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='order_progress',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Accepted', 'Accepted'), ('Despached', 'Despached'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered')], default='Ordered', max_length=20),
        ),
    ]
