# Generated by Django 5.0.6 on 2024-09-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_order_order_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='house_house',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
