# Generated by Django 5.0.6 on 2024-08-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_customuser_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bv_active_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='designation',
            field=models.CharField(choices=[('Executive', 'Executive'), ('Cheif Executive', 'Cheif Executive'), ('Manager', 'Manage'), ('General Manager', 'General Manager'), ('Director', 'Director')], default='Executive', max_length=20),
        ),
    ]
