# Generated by Django 5.0.6 on 2024-08-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_customuser_bv_active_status_customuser_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_volume',
            name='purchase_bv',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='business_volume',
            name='balance_bv',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='business_volume',
            name='bv_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='business_volume',
            name='total_bv',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='designation',
            field=models.CharField(choices=[('Executive', 'Executive'), ('Cheif Executive', 'Cheif Executive'), ('Manager', 'Manager'), ('General Manager', 'General Manager'), ('Director', 'Director')], default='Executive', max_length=20),
        ),
    ]
