# Generated by Django 5.0.6 on 2024-08-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_accountdetails_ifsc_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cast',
            field=models.CharField(default='Nil', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='designation',
            field=models.CharField(choices=[('Executive', 'Executive'), ('Chief Executive', 'Chief Executive'), ('Manager', 'Manager'), ('General Manager', 'General Manager'), ('Director', 'Director')], default='Executive', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(default='Nil', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user'), ('semi-admin', 'semi-admin'), ('finance', 'finance'), ('marketing', 'markenting'), ('central_franchise', 'central_franchise'), ('district_franchise', 'district_franchise'), ('zonel_franchise', 'zonel_franchise'), ('mobile_franchise', 'mobile_franchise')], default='user', max_length=20),
        ),
    ]
