# Generated by Django 5.0.6 on 2024-09-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_customuser_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='branch_name',
            field=models.CharField(max_length=100),
        ),
    ]
