# Generated by Django 5.0.6 on 2024-09-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_customuser_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
